name:  SystemExtensions CD Pipeline

on:
  push:
    branches:
      - master

jobs:

  build:
    environment: Default
    strategy:
      matrix:
        targetplatform: [x64]

    runs-on: windows-latest

    env:
      Configuration: Release
      Solution_Path: SystemExtensions.sln
      Test_Project_Path: SystemExtensions.Tests\SystemExtensions.NetStandard.Tests.csproj
      DI_Test_Project_Path: SystemExtensions.DependencyInjection.Tests\SystemExtensions.NetStandard.DependencyInjection.Tests.csproj
      Source_Project_Path: SystemExtensions.NetStandard\SystemExtensions.NetStandard.csproj
      Actions_Allow_Unsecure_Commands: true

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.202'

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.1

    - name: Restore project
      run: msbuild $env:Solution_Path /t:Restore /p:Configuration=$env:Configuration /p:RuntimeIdentifier=$env:RuntimeIdentifier
      env:
        RuntimeIdentifier: win-${{ matrix.targetplatform }}

    - name: Build SystemExtensions.NetStandard project
      run: dotnet build SystemExtensions.NetStandard -c $env:Configuration

    - name: Build SystemExtensions.NetStandard.DependencyInjection project
      run: dotnet build SystemExtensions.NetStandard.DependencyInjection -c $env:Configuration

    - name: Push SystemExtensions.NetStandard nuget package
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
         PROJECT_FILE_PATH: SystemExtensions.NetStandard\SystemExtensions.NetStandard.csproj
         NUGET_KEY: ${{secrets.NUGET_API_KEY}}

    - name: Push SystemExtensions.NetStandard.DependencyInjection nuget package
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
         PROJECT_FILE_PATH: SystemExtensions.NetStandard.DependencyInjection\SystemExtensions.NetStandard.DependencyInjection.csproj
         NUGET_KEY: ${{secrets.NUGET_API_KEY}}