name:  SystemExtensions CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:

  build:

    strategy:
      matrix:
        targetplatform: [x64]

    runs-on: windows-latest

    env:
      Solution_Path: SystemExtensions.sln
      Test_Project_Path: SystemExtensions.Tests\SystemExtensions.NetStandard.Tests.csproj
      DI_Test_Project_Path: SystemExtensions.DependencyInjection.Tests\SystemExtensions.NetStandard.DependencyInjection.Tests.csproj
      Sec_Test_Project_Path: SystemExtensions.NetStandard.Security.Tests\SystemExtensions.NetStandard.Security.Tests.csproj
      Source_Project_Path: SystemExtensions.NetStandard\SystemExtensions.NetStandard.csproj
      Actions_Allow_Unsecure_Commands: true

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.1

    - name: Execute Unit Tests
      run: dotnet test $env:Test_Project_Path

    - name: Execute DI Unit Tests
      run: dotnet test $env:DI_Test_Project_Path

    - name: Execute Security Unit Tests
      run: dotnet test $env:Sec_Test_Project_Path

    - name: Restore Project
      run: msbuild $env:Solution_Path /t:Restore /p:Configuration=$env:Configuration /p:RuntimeIdentifier=$env:RuntimeIdentifier
      env:
        Configuration: Debug
        RuntimeIdentifier: win-${{ matrix.targetplatform }}